### ISSUE TITLE
non-ASCII characters in README causes install to fail

### ISSUE THREAD

**Issue by schristley** [dustinkirkland/python-petname#11]
```
$ python3 --version
Python 3.6.9
$ pip3 install petname
Collecting petname
  Downloading https://files.pythonhosted.org/packages/8e/a5/348c90b3fb09d7bd76f7dacf1b92e251d75bfbe715006cb9b84eb23be1b1/petname-2.6.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ahsh1i5c/petname/setup.py", line 23, in <module>
        long_description = fh.read()
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 32: ordinal not in range(128)
```

**Comment by dustinkirkland** [comment]
Hmm, I'm unable to reproduce this problem....

# pip3 install petname
Collecting petname
  Downloading petname-2.6.tar.gz (8.4 kB)
Building wheels for collected packages: petname
  Building wheel for petname (setup.py) ... done
  Created wheel for petname: filename=petname-2.6-py3-none-any.whl size=8129 sha256=063d45aadbf9afee777d6305895ed5cde23b71831f125b4d548ffbce0f08756a
  Stored in directory: /root/.cache/pip/wheels/df/d0/f7/5bb2e3528016cf736839ec867275e2ecc9c01e0e26c7596fe3
Successfully built petname
Installing collected packages: petname
Successfully installed petname-2.6

**Comment by dustinkirkland** [comment]
# python3 --version
Python 3.8.2

**Comment by schristley** [comment]
Sorry, forgot to update. Yes, it is definitely related to the python version. I updated to a newer ubuntu (18.04 -> 20.04) which has a newer python and the problem went away. So if there's no need to support the older python version then can probably close this issue with will not fix.

**Comment by ethho** [comment]
Should we anticipate support for `3.6.9`?

**Comment by asottile** [comment]
looks like this was fixed by https://github.com/dustinkirkland/python-petname/commit/815e50afa74eb8aa743cdda145967fa36fe01af8 -- just needs a pypi release

**Comment by dustinkirkland** [comment]
Thank you for reporting this issue! This has been resolved in version 2.7 with the addition of UTF-8 encoding in setup.py (commit 815e50a).

The fix includes:
- Using `io.open()` with `encoding='utf-8'` when reading README.md
- Adding a try/except block to gracefully handle any encoding issues

The current codebase (version 2.8) includes this fix. Once the next release is published to PyPI, this issue will be fully resolved for end users.

Closing this as the code fix is complete.
