### ISSUE TITLE
install error ,UnicodeDecodeError: 'gbk' codec can't decode byte 0x92 in position 34: illegal multibyte sequence

### ISSUE THREAD

**Issue by ZenithNovaTech** [dustinkirkland/python-petname#15]
error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [6 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Administrator\AppData\Local\Temp\pip-install-42tba8cl\petname_f1e18b16d48d410b900a9f6277c7d5b2\setup.py", line 23, in <module>
          long_description = fh.read()

**Comment by liqiujiong** [comment]
same question
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)] on win32
pip 24.1.2 
solve it:
'''
set PYTHONUTF8=1
pip install -r requirements.txt
'''

**Comment by dustinkirkland** [comment]
Thank you for reporting this issue! This encoding problem was resolved in version 2.7 with the same fix that addressed issue #11.

The current setup.py includes:
- UTF-8 encoding specification when reading files
- A try/except block to handle UnicodeDecodeError gracefully

The workaround mentioned (`set PYTHONUTF8=1`) should no longer be necessary once the updated package is released to PyPI.

Closing this as the code fix is already in place (version 2.8 unreleased).
